Update Elyra image to v2.0.1
opendatahub-io/odh-manifests pull request #297
Opened 2021-01-28 18:55 UTC by akchinSTC

- Adds support for Tekton in Kubeflow Pipelines

Dependent on PR: https://github.com/opendatahub-io/s2i-lab-elyra/pull/16

2021-01-29 14:36 UTC, anishasthana commented
/ok-to-test

2021-02-04 16:42 UTC, crobby commented
This likely needs a rebase to get the tests passing.  There was a change to airflow that forced us to change some of the tests.

2021-02-04 16:46 UTC, vpavlin commented
/do-not-merge

2021-02-04 16:48 UTC, vpavlin commented
/hold

2021-02-04 16:49 UTC, vpavlin commented
The PR https://github.com/opendatahub-io/s2i-lab-elyra/pull/16 need to be merged first and a release needs to be created before we merge this

2021-03-09 14:21 UTC, harshad16 reviewed
/lgtm

https://quay.io/repository/thoth-station/s2i-lab-elyra?tag=v0.0.6&tab=tags

2021-03-10 16:06 UTC, anishasthana commented
The test is failing with:
```
ERROR:root:Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="s2i-minimal-notebook:v0.0.7"]"}
```

2021-03-10 19:40 UTC, nakfour commented
@akchinSTC can you please rebase, we have a Z-stream release scheduled to start tomorrow, if this needs to make it in, it has to merge today.

2021-03-16 21:01 UTC, nakfour commented
/lgtm

2021-03-16 21:01 UTC, nakfour approved these changes

2021-03-16 21:37 UTC, akchinSTC commented
@nakfour - thanks for the quick review!

2021-03-17 01:44 UTC, anishasthana commented
@harshad16 are we good to unhold the PR?

2021-03-17 03:26 UTC, harshad16 requested changes
the pr can be unheld.
just a small change to be made.

2021-03-17 03:26 UTC, harshad16 commented on jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
>          kind: ImageStreamTag
```suggestion
        kind: DockerImage
```

2021-03-17 13:54 UTC, LaVLaS commented
/test all

2021-03-17 16:15 UTC, akchinSTC commented on jupyterhub/notebook-images/overlays/build/elyra-notebook-buildconfig.yaml
>          kind: ImageStreamTag
updated

2021-03-17 16:41 UTC, anishasthana commented
/unhold

2021-03-17 19:53 UTC, harshad16 reviewed
/lgtm

2021-03-17 19:54 UTC, merged