Added ImageChange trigger to the JupyterHub deployment config
opendatahub-io/odh-manifests pull request #334
Opened 2021-03-01 14:16 UTC by mroman-redhat

The trigger is based on an older implementation. It should be changed later so it does not use :latest image.

Closes: #310

2021-03-01 15:13 UTC, vpavlin commented
I believe we removed this in the past to avoid issues with endless redeployments. We need to carefully verify this before we add it back

2021-03-04 04:40 UTC, LaVLaS requested changes

2021-03-04 04:40 UTC, LaVLaS commented on jupyterhub/jupyterhub/base/jupyterhub-dc.yaml
> +        -wait-for-database
Currently this is being parsed as a string, this needs a space after the `-` to make it a list

2021-03-17 03:38 UTC, LaVLaS approved these changes

2021-03-17 03:39 UTC, merged