Add monitoring to Trino
opendatahub-io/odh-manifests pull request #475
Opened 2021-08-31 17:23 UTC by rimolive

This PR implements additional k8s objects to add prometheus monitoring capabilities in Trino. This change will require the new `quay.io/opendatahub/trino:361` image as it contains the prometheus library to export metrics.

## Testing instructions
* Deploy the trino/base manifest in a cluster
  * You can use the command `kustomize build trino/base | {oc|kubectl} apply -n <namespace> -f -`
* Check if no pods are in `CrashLookbakOff` or `Error` state
* Check if the trino-service Service exposes the ports 8080 and 8082 (the last one is the prometheus port)
* As an optional step, create a route for trino-service Service and access the hostname. You should see the prometheus metrics.

2021-08-31 18:40 UTC, anishasthana requested changes
Could we also update the monitoring stack that is is deployed (https://github.com/opendatahub-io/odh-manifests/tree/master/prometheus/operator/base) to have an additional pod or service monitor that would scrape trino metrics?

2021-08-31 18:40 UTC, anishasthana commented on trino/base/trino-config-monitoring-secret.yaml
> +        type: GAUGE
Missing new line

2021-08-31 18:40 UTC, anishasthana commented on trino/base/trino-config-secret.yaml
> +
Extra new line?

2021-09-01 14:21 UTC, anishasthana commented on trino/base/trino-service.yaml
> +    - name: http
Could we give this a better name than http?

2021-09-01 19:29 UTC, anishasthana reviewed
Changes lgtm!

2021-09-01 19:56 UTC, LaVLaS approved these changes
/lgtm

Assuming CI runs cleanly

2021-09-02 03:23 UTC, anishasthana commented
/retest

2021-09-03 19:25 UTC, anishasthana commented
/retest

2021-09-07 12:16 UTC, rimolive commented
/retest

2021-09-07 15:54 UTC, anishasthana commented
/lgtm

2021-09-07 16:53 UTC, merged