Update Spark Operator to support ocp 4.9
opendatahub-io/odh-manifests pull request #506
Opened 2021-11-18 17:24 UTC by rimolive

2021-11-18 23:40 UTC, LaVLaS requested changes

2021-11-18 23:40 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/rolebinding.yaml
> +  namespace: "{{ meta.namespace }}"
This should use the kfdef parameter for the target namespace `$(namespace)`

2021-11-18 23:40 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/role.yaml
> +  namespace: "{{ meta.namespace }}"
iirc, you can leave the namespace out and kfctl will automatically apply the correct namespace based on where the kfdef exists

2021-11-18 23:40 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/role.yaml
> +kind: Role
I have to confirm but I think the spark-operator had clusterwide permissions

2021-11-18 23:40 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/deployment.yaml
> +          value: "{{ meta.namespace }}"
This variable won't work kfdef deployment.
I think the value is provided by OLM based on the OperatorGroup in the namespace
```
valueFrom:
  fieldRef:
    fieldPath: metadata.annotations['olm.targetNamespaces']
```

2021-11-29 15:31 UTC, nakfour commented
@rimolive the CI tests are failing on the ODH dashboard, try rebasing.

2021-11-29 17:36 UTC, rimolive commented
/retest

2021-12-01 15:51 UTC, LaVLaS requested changes

2021-12-01 15:51 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/rolebinding.yaml
> +  kind: ClusterRole
This should be a `Role` based on the role you are creating just for spark

2021-12-01 15:51 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/role.yaml
> +  name: edit-resources
Can you add `spark` to the name to show that this was created for the spark operator deployment?

2021-12-02 17:09 UTC, LaVLaS commented on radanalyticsio/spark/cluster/base/rolebinding.yaml
> +  kind: ClusterRole
Closing this because the `Role` that is created should be a `ClusterRole`

2021-12-03 20:53 UTC, LaVLaS requested changes

2022-03-02 05:37 UTC, LaVLaS commented
Closing this since the work is being completed in #509

2022-03-02 05:37 UTC, closed without merging