Rename kfp-tekton component to ml-pipelines
opendatahub-io/odh-manifests pull request #611
Opened 2022-08-01 20:15 UTC by rimolive

2022-08-01 20:17 UTC, anishasthana requested changes

2022-08-01 20:17 UTC, anishasthana commented on kfdef/pipelines_prototype.yaml
>            path: kfp-tekton
This line and the following line need to be updated.

2022-08-01 23:49 UTC, anishasthana approved these changes
/lgtm

2022-08-02 13:34 UTC, gmfrasca approved these changes

2022-08-02 13:38 UTC, merged