Add OWNERS file to each component
opendatahub-io/odh-manifests pull request #666
Opened 2022-08-30 00:39 UTC by LaVLaS

* Add OWNERS file to ml-pipelines
* Add owners file for pachyderm
* Add ceph-nano OWNERS file
* Add OWNERS file for model-mesh
* Add OWNERS to odh-notebook-controller
* Add OWNERS servicemesh
* Add OWNERS trino
* Add OWNERS to odh-dashboard
* Add OWNERS to hue
* Add OWNERS for jupyterhub

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

## Description
Adds an OWNERS file to every component to ensure that the CI system requires PR reviews from contributors closest to the code change

Closes #646 

## How Has This Been Tested?
N/A

## Merge criteria:
Signoff from the relevant component owners

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2022-08-30 10:44 UTC, accorvin commented
/approve

2022-08-30 13:09 UTC, LaVLaS commented
/hold 
Putting a hold on this until I get approval from key contributors in the OWNERS file

2022-08-30 14:47 UTC, Jooho commented
/lgtm

2022-08-30 15:05 UTC, crobby commented
In general, I think we should strive to have more than 1 person listed in each owners file

2022-08-30 15:06 UTC, anishasthana requested changes

2022-08-30 15:06 UTC, anishasthana commented on model-mesh/OWNERS
> +approvers:
Can you add me to this list as well? @crobby

2022-08-30 15:08 UTC, anishasthana reviewed
We have a couple of OWNERS files with single approvers. Imo we should ahve at least 2 for each component.

2022-08-30 15:54 UTC, LaVLaS commented
/unhold

2022-08-30 21:27 UTC, LaVLaS commented
/retest

2022-09-01 13:21 UTC, LaVLaS commented
/approve

Approving based on previous +1

2022-09-01 13:28 UTC, LaVLaS commented
/lgtm

2022-09-01 14:46 UTC, accorvin commented
/lgtm

2022-09-01 14:48 UTC, merged