Add metrics port for modelmesh infra pods
opendatahub-io/odh-manifests pull request #690
Opened 2022-10-28 18:00 UTC by rimolive

Signed-off-by: Ricardo Martinelli de Oliveira <rmartine@redhat.com>

## Description
Add metrics port for modelmesh services

## How Has This Been Tested?
* Deploy modelmesh kfdef
* Configure prometheus to scrape metrics from the following service objects:
    * odh-model-controller-metrics-service
    * modelmesh-controlle
* Check if the targets are available

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2022-10-28 18:19 UTC, anishasthana approved these changes

2022-10-28 18:19 UTC, anishasthana commented on model-mesh/manager/manager.yaml
> +    control-plane: modelmesh-controller
Missing newline

2022-10-28 19:37 UTC, anishasthana commented
This is actually a little premature. /hold

2022-10-28 19:37 UTC, anishasthana commented
We will be raising a PR later for a bulk update of the manifests related to modelmesh-serving

2022-10-28 19:37 UTC, anishasthana commented
/unapprove

2022-10-28 19:38 UTC, anishasthana requested changes
This PR needs to be closed out.

2022-11-04 11:03 UTC, LaVLaS commented
Closing based on the recommendation of @anishasthana

2022-11-04 11:03 UTC, closed without merging