Integrate the new prebuild image notebooks into upstream
opendatahub-io/odh-manifests pull request #702
Opened 2022-11-15 15:18 UTC by atheo89

This PR includes all the necessary changes to switch from jupyterhub to jupyter notebooks. The corresponding open issue is the https://github.com/opendatahub-io/odh-manifests/issues/671

## Description

The old Thoth images from `jupyterhub/notebook-images/overlays/additional` are replaced with the new set of notebooks into `jupyter-notebooks/base`.

Below is the folder tree of the new folder structure under the root path of the repository. 
```
├── jupyter-notebooks
│   └── base
│       ├── generic-data-science-notebook-imagestream.yaml
│       ├── kustomization.yaml
│       ├── minimal-gpu-notebook-imagestream.yaml
│       ├── minimal-notebook-imagestream.yaml
│       ├── pytorch-notebook-imagestream.yaml
│       └── tensorflow-notebook-imagestream.yaml
```
These images are stored in (https://github.com/opendatahub-io/notebooks) and are built with Openshift CI and mirrored to Quay (https://quay.io/repository/opendatahub/notebooks).

Updated testing KfDef `tests/setup/odh-core.yaml` to use the `jupyter-notebooks` folder

Last, as part of this transition, refactored the test notebooks `tests/resources/notebook-controller/notebooks` as presented below:
```
├── tests
│  ...
│   ├── resources
│   │   ...
│   │   ├── notebook-controller
│   │   │   ├── notebooks
│   │   │   │   ├── generic-data-science-oauth-notebook.yaml
│   │   │   │   ├── kubeflow-jupyter-oauth-notebook.yaml
│   │   │   │   ├── minimal-gpu-oauth-notebook.yaml
│   │   │   │   ├── minimal-oauth-notebook.yaml
│   │   │   │   ├── pytorch-oauth-notebook.yaml
│   │   │   │   └── tensorflow-oauth-notebook.yaml
```

## How Has This Been Tested?

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2022-11-15 16:17 UTC, samuelvl requested changes

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/generic-data-science-notebook-imagestream.yaml
> +    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/jupyter/datascience/ubi8-python-3.8"
```suggestion
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/datascience/ubi8-python-3.8"
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/generic-data-science-notebook-imagestream.yaml
> +  name: s2i-generic-data-science-notebook
```suggestion
  name: jupyter-datascience-notebook
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/generic-data-science-notebook-imagestream.yaml
> +    opendatahub.io/notebook-image-name: "Standard Data Science"
```suggestion
    opendatahub.io/notebook-image-name: "Jupyter Data Science"
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/generic-data-science-notebook-imagestream.yaml
> +      # if you change the image tag, change the "-N" on the tag name immediately below
This comment doesn't apply anymore:

```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/minimal-gpu-notebook-imagestream.yaml
> +    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/jupyter/minimal/ubi8-python-3.8"
```suggestion
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/notebooks/tree/main/jupyter/minimal/ubi8-python-3.8"
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/minimal-notebook-imagestream.yaml
> +apiVersion: image.openshift.io/v1
```suggestion
---
apiVersion: image.openshift.io/v1
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/minimal-notebook-imagestream.yaml
> +  name: s2i-minimal-notebook
```suggestion
  name: jupyter-minimal-notebook
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/minimal-notebook-imagestream.yaml
> +      # in a downstream build "latest" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/minimal-notebook-imagestream.yaml
> +    # in a downstream build "rhodsversion" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +apiVersion: image.openshift.io/v1
```suggestion
---
apiVersion: image.openshift.io/v1
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +    opendatahub.io/notebook-image-order: "40"
```suggestion
    opendatahub.io/notebook-image-order: "4"
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +      # in a downstream build "latest" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +    # in a downstream build "rhodsversion" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +    name: "py3.8-cuda-11.4.2-2"
```suggestion
    name: "py3.8-v1"
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/pytorch-notebook-imagestream.yaml
> +  name: pytorch
```suggestion
  name: jupyter-pytorch-gpu-notebook
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/tensorflow-notebook-imagestream.yaml
> +  name: tensorflow
```suggestion
  name: jupyter-tensorflow-gpu-notebook
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/tensorflow-notebook-imagestream.yaml
> +      # in a downstream build "latest" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/tensorflow-notebook-imagestream.yaml
> +    # in a downstream build "rhodsversion" will be replaced
```suggestion
```

2022-11-15 16:17 UTC, samuelvl commented on jupyter-notebooks/base/tensorflow-notebook-imagestream.yaml
> +    name: "py3.8-cuda-11.4.2-2"
```suggestion
    name: "py3.8-v1"
```

2022-11-15 16:17 UTC, samuelvl commented on tests/resources/notebook-controller/notebooks/generic-data-science-oauth-notebook.yaml
> ----
Do not remove yaml header

2022-11-15 16:17 UTC, samuelvl commented on tests/resources/notebook-controller/notebooks/generic-data-science-oauth-notebook.yaml
> +          image: qquay.io/opendatahub/notebooks:jupyter-datascience-ubi8-python-3.8
We want to test the images imported by the previous image streams, not those in quay.io. For example:

```suggestion
          image: image-registry.openshift-image-registry.svc:5000/opendatahub/jupyter-datascience-notebook:py3.8-v1
```

Review the other notebooks too.

2022-11-18 09:58 UTC, atheo89 commented
/retest

2022-11-18 12:47 UTC, samuelvl commented
@atheo89 Tests are failing because of:

```
 Standard error from the command:
./run_robot_test.sh: line 194: lsb_release: command not found
You are using pip version 21.3.1, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[ERROR] PID 454: test/lib/log/stacktrace.sh:0: `return "${return_code}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: test/lib/log/stacktrace.sh:0: `return "${return_code}"`
[INFO] 		  2: test/lib/util/trap.sh:65: os::log::stacktrace::print
[INFO] 		  3: test/lib/cmd.sh:10: os::util::trap::err_handler
[INFO] 		  4: operator-tests/odh-manifests/basictests/dashboard.sh:66: os::cmd::expect_success
[INFO] 		  5: operator-tests/odh-manifests/basictests/dashboard.sh:74: test_odh_dashboard_ui
[INFO]   Exiting with code 1.
failed: /root/peak/operator-tests/odh-manifests/basictests/dashboard.sh 
```

This is not related with your PR, could you take a look? @LaVLaS

2022-11-24 14:17 UTC, LaVLaS commented
/retest

2022-11-28 13:26 UTC, LaVLaS commented
@atheo89 I will be merging this today after I finish and manual test while I finish a PR to resolve the CI test issues

2022-11-29 09:02 UTC, atheo89 commented
>Can you change the component folder to `notebook-images` or was the `notebooks-images` intentional?
@LaVLaS I push the changes (it was a typo error)

2022-11-29 14:17 UTC, LaVLaS approved these changes
/lgtm

2022-11-29 14:30 UTC, merged