Update logging, & spec.
opendatahub-io/odh-manifests pull request #800
Opened 2023-04-27 15:45 UTC by HumairAK

## Description
This change adds more detailed logging as well as makes adding a port for external storage optional. New sample configurations for aws s3 examples are also provided.

## How Has This Been Tested?
Tested live on ocp cluster. With aws s3 storage used as external storage.

## Merge criteria:
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-04-27 18:13 UTC, rimolive requested changes

2023-04-27 18:13 UTC, rimolive commented on data-science-pipelines-operator/samples/dspa_all_fields.yaml
> +    - type: UserInterfaceReady
We removed that condition. Better remove from that file.

2023-04-27 20:27 UTC, DharmitD approved these changes
/Approve

2023-05-08 13:40 UTC, HumairAK commented
closing in favor of: https://github.com/opendatahub-io/odh-manifests/pull/803

2023-05-08 13:40 UTC, closed without merging