Update deploy-python-model-quickstart.yaml
opendatahub-io/odh-manifests pull request #835
Opened 2023-05-31 18:43 UTC by jjasghar

## Description
- Updated to the "prediction_s_" not "prediction" per the flask app.
- Fixed the formating with "<" not being able to be read via the tutorial software.

## How Has This Been Tested?
Verified in my test env.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2023-05-31 20:54 UTC, andrewballantyne commented
@kywalker-rh Not sure who reviews our Quick Starts -- but there is a slight change to the python one needing a content review.

2023-06-01 18:08 UTC, kywalker-rh commented
> 

@andrewballantyne I'm not sure either. Maybe Audrey?

2023-06-05 20:24 UTC, andrewballantyne commented
/ok-to-test

2023-06-07 13:07 UTC, dchourasia requested changes

2023-06-07 13:07 UTC, dchourasia commented on odh-dashboard/apps/jupyter/deploy-python-model-quickstart.yaml
> +        curl -X POST -d '{"hello" ":" "world"}' YOUR_ROUTE/predictions
```suggestion
        curl -X POST -d '{"hello" : "world"}' YOUR_ROUTE/predictions
```

2023-06-07 13:07 UTC, dchourasia commented on odh-dashboard/apps/jupyter/deploy-python-model-quickstart.yaml
> +        curl -X POST -d '{"hello" ":" "world"}' http://example.apps.organization.abc3.p4.openshiftapps.com/predictions
```suggestion
        curl -X POST -d '{"hello" : "world"}' http://example.apps.organization.abc3.p4.openshiftapps.com/predictions
```

2023-06-07 20:15 UTC, andrewballantyne commented
/retest

Yeah, they gotta be a flake... you're changing yaml content. Let us retest and see.

2023-06-08 12:23 UTC, andrewballantyne commented
/retest

2023-06-08 14:13 UTC, andrewballantyne commented
@LaVLaS @VaishnaviHire is our tests really that flaky? I'm not sure how this PR could break a test, as it's just quickstart content.

2023-06-14 16:55 UTC, andrewballantyne commented
/retest

2023-06-14 19:12 UTC, LaVLaS commented
> @LaVLaS @VaishnaviHire is our tests really that flaky? I'm not sure how this PR could break a test, as it's just quickstart content.

Check the logs to see that the dashboard test is failing because the Jupyter tile is not visible when it attempts to spawn a notebook. See [Screenshots](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/opendatahub-io_odh-manifests/835/pull-ci-opendatahub-io-odh-manifests-master-411-odh-manifests-e2e/1666782927821737984/artifacts/odh-manifests-e2e/e2e/artifacts/ods-ci-2023-06-08-13-33-mQZNtPgk8A/) from the test run.  Without debugging the CI environment while it is running this PR should rebase on top of the latest dashboard version

2023-06-15 13:21 UTC, andrewballantyne commented
Okay sweet... we got a success.

/lgtm

2023-06-15 13:22 UTC, andrewballantyne commented
Awesome, thanks for your PR @jjasghar -- we got through the CI troubles 😄 this should merge automatically when the bot finishes up.

2023-06-15 13:25 UTC, merged